trigger:
  - dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildDockerImage
  jobs:
  - job: BuildPushImage
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        docker login -u $(DOCKER_ID) -p $(DOCKER_PASS)
        docker build -t alielhabal70/sprint-boot:$(Build.BuildId) .
        docker push alielhabal70/sprint-boot:$(Build.BuildId)
        docker tag alielhabal70/sprint-boot:$(Build.BuildId) alielhabal70/sprint-boot:latest
        docker push alielhabal70/sprint-boot:latest
