trigger:
  - dev

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildDockerImage
  jobs:
  - job: BuildPushImage
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        docker login -u $(DOCKER_ID) -p $(DOCKER_PASS)
        docker build -t Ali3Elhabal/sprint-boot:$(Build.BuildId) .
        docker push Ali3Elhabal/sprint-boot:$(Build.BuildId)
        docker tag Ali3Elhabal/sprint-boot:$(Build.BuildId) Ali3Elhabal/sprint-boot:latest
        docker push Ali3Elhabal/sprint-boot:latest

